name: ll-env

channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - numpy=1.21.0
  - scipy=1.5.3
  - matplotlib=3.4.2
  - h5py=2.10.0
  - scikit-learn=1.1.1
  - seaborn=0.11.2

  - cudatoolkit=11.3
  - pytorch=1.10.2
  - torchvision=0.11.3

  - openmpi=4.0.2
  - mpi4py=3.0.3